add_newline = false
format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$docker_context\
$helm\
$terraform\
$typst\
$vagrant\
$conda\
$meson\
$memory_usage\
$direnv\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$netns\
$shell\
$character"""

[character]
format = "$symbol "
success_symbol = "[](bold white)"
error_symbol = "[](bold red)"

# Package Managers
[package] # Hidden
symbol = "󰏗 "

[nodejs]
symbol = " "
version_format = "${major}"

[conda]
symbol = " "

[meson]
symbol = "󰔷 "

[nix_shell]
symbol = " "

# Programming Languages
[python]
symbol = " "
version_format = "${major}.${minor}"

[rust]
symbol = "󱘗 "

[zig]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[deno]
symbol = " "

# Git
[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

# Clouds
[aws]
symbol = "  "

[gcloud]
symbol = ""
format = "on [$symbol $domain]($style)"

# Containers
[docker_context]
symbol = " "

# System
[directory]
read_only = " 󰌾"

[hostname]
ssh_symbol = " "

[memory_usage]
symbol = "󰍛 "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Kali = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
